### ISSUE TITLE
Example on how to use this with code in /tests and /benches (opposed to code at /src)

### ISSUE THREAD

**Issue by MOZGIII** [gnzlbg/cargo-asm#64]
Hi, I need an example on how to use this with code in `/tests` and `/benches` directories (opposed to code at `/src`). I'm referring to standard cargo project structure directories, abd the code I can call with `cargo test` and `cargo +nightly bench`.

Thanks in advance.

**Comment by gnzlbg** [comment]
Dup of #21 .

**Comment by MOZGIII** [comment]
Sorry, but I don't see how it's a dup. There's no concrete invocation example. Can you plese provide a summary? Is it wointfix?

**Comment by MOZGIII** [comment]
Just to clarify: I don't see how it's a dup because cargo bench does not seem to be about just some particular binary that's under my control - it's something managed by the framework (cargo).

**Comment by gnzlbg** [comment]
That issue is about supporting generating assembly for anything that's not a `lib` target. Each benchmark in `benches/`, test in `tests/`, example in `exmaples/` and any other binary target are just normal binaries under the hood.

> Is it wointfix?

We should add support for this, but as the issue mentions, it isn't trivial. Until that issue is fixed `cargo asm`/`cargo llvm-ir` only work for `lib` targets. You can try to hack support for other targets, but YMMV. If you do, let us know how it went in that issue.

**Comment by MOZGIII** [comment]
Thanks for making it clear for me! I already looked into the code a bit, I doubt I'll be able to help at this point.

**Comment by gnzlbg** [comment]
Most of the work would probably need to happen in `cargo metadata` anyways. If it would tell us which files belong to which target, that issue would probably be trivial to fix.

**Comment by l4l** [comment]
It will work just by passing --benches/--tests to cargo. Isn't it a good solution for that problem? It might be not as generic as it could be, though the interface itself is straightforward and consistent
